### ISSUE TITLE
你好, 这个框架还没有任何文档说明吗?

### ISSUE THREAD

**Issue by daniel-du** [liuyangming/ByteJTA#1]
你好, 这个框架还没有任何文档说明吗? 前连天看了一下你这里的ByteTCC 然后发现, 还有一个 两段式的框架. 就点进来看了一下. 发现没有文档. 这个是还没有完成吗?

**Comment by liuyangming** [comment]
使用文档：[https://github.com/liuyangming/ByteTCC/wiki](https://github.com/liuyangming/ByteTCC/wiki)

**Comment by daniel-du** [comment]
谢谢你的回复.
