### ISSUE TITLE
TransactionXid#branchQualifier 没有 set 到 TransactionContext

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteJTA#7]
```TransactionXid#branchQualifier``` 有生成并 set 到 Archive，但是要在 TransactionContext get branchQualifier 是取不到的，这个问题能解决下吗？

***在(ByteTCC)事务过程中要获取 branchQualifier 的需求场景***

**Comment by liuyangming** [comment]
TransactionContext是用于远程节点之间传播事务上下文。上下文只需要包含全局ID（globalXid）信息即可，不需要分支ID（branchQualifier）。分支ID仅在分支事务中自己管理XAResource使用。
